name: Publish Mod

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew build

      - name: Publish mod
        run: ./gradlew forge:curseforge fabric:curseforge forge:modrinth fabric:modrinth